name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update GitHub Profile README
      uses: theboi/github-update-readme@main
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      with:
        header: "Hey, I'm Curious-01! 👋"
        subhead: "Currently bla-bla."
        footer: "**Learn more about me at [curious-01.github.io](https://curious-01.github.io)!**"
        ref: "main"
        excludeActivity: '["WatchEvent"]'
        excludeRepo: '["YogeshJain96/YogeshJain96"]'
